# Cloudflare/lskypro-bot/wrangler.toml
name = 'lsky-telegram-worker'

# Worker 入口文件
main = "lskypro-telegram-worker.js"

# Cloudflare Workers 兼容日期
compatibility_date = "2026-08-19"

# 如果后续需要 Node.js 兼容能力，可以打开
# compatibility_flags = ["nodejs_compat"]

# D1 数据库绑定
# 注意：database_id 必须替换成你自己的 D1 数据库 ID
[[d1_databases]]
binding = "DB"
database_name = "lsky-telegram-worker"
database_id = "e5a1c753-525a-4876-8f74-da075554791c"

[observability]
enabled = false
head_sampling_rate = 1
[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true
[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[vars]
ALLOWED_TELEGRAM_USER_IDS = "1050736994"
LSKY_API_URL = "https://img.orionc.me/api/v1/upload"
LSKY_PERMISSION = "1"
SHLINK_API_URL = "https://go.orionc.me"
SHORTEN_ALLOWED_HOSTS = "img.orionc.me"
MAX_FILE_MB = "25"
MAX_UPLOAD_QUEUE_IMAGES = "100"
ALBUM_WAIT_SECONDS = "2"
UPLOAD_CONCURRENCY = "2"
LOG_UPLOAD_TIMINGS = "true"
REQUEST_TIMEOUT_SECONDS = "60"
